name: Build

on:
  push:

permissions:
  contents: read

jobs:
  run_tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: WHS-FRC-3467/W8-Library
          ref: ${{ github.ref }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build Robot Code
        run: ./gradlew build -x test
      - name: Test Robot Code
        run: ./gradlew test
      - name: Check Formatting
        run: ./gradlew spotlessCheck
